[package]
name = "guile"
version = "0.0.2"
authors = ["David Li <li.davidm96@gmail.com>"]

description = "Safe bindings to GNU Guile."
repository = "https://github.com/lidavidm/guile-rs"
license = "LGPL-3.0"

[dependencies]
libc="0.2"

[dependencies.guile-sys]
path = "guile-sys"
version = "0.1.1"

[[bin]]
name = "shell"
path = "examples/shell.rs"
